### ISSUE TITLE
Font character space

### ISSUE THREAD

**Issue by metingul** [busel7/DMDESP#3]
Hello,
I created some of fonts that are used with DMD2 library. When I use that fonts with DMDESP the space is too long, how can I set the space size?

thank you.

**Comment by busel7** [comment]
Hi,

try to look dmdesp font template, here is font example https://github.com/busel7/DMDESP/blob/master/fonts/EMSans5x6.h

at part of character size mapping, mine is 0x01 for space

**Comment by metingul** [comment]
I think the libraries discard size of space that is specified in the font file. The library may have a function about calculation of space char.?
because the space data is also very short width in font file.
Please advice.

thank you.

**Comment by metingul** [comment]
I found a code in Birmap.cpp about font space;
I removed line#591 and I insert space width manually.

```
if (ch == ' ') {
        // Font may not have space, or it is zero-width.  Calculate
        // the real size and fill the space.
        // int spaceWidth = charWidth('n'); //  I remove this line
		int spaceWidth = 2; // add space width manually.
        fill(x, y, spaceWidth, height, !_textColor);
        return spaceWidth;
    }
```
